"""
CoinScopeAI Paper Trading — ML Signal Engine Integration
===========================================================
Feeds real-time OHLCV candles through the ML v2 feature pipeline
and model inference to generate trading signals.

Maintains a rolling window of candles per symbol, computes features
on each new closed candle, and runs model prediction.
"""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger("coinscopeai.paper_trading.signals")


@dataclass
class TradingSignal:
    """A trading signal generated by the ML engine."""
    symbol: str
    direction: str        # LONG, SHORT, or NEUTRAL
    confidence: float     # Model probability for the predicted class
    edge: float           # Confidence minus neutral probability
    predicted_class: int  # 0=SHORT, 1=NEUTRAL, 2=LONG
    probabilities: Dict[str, float] = field(default_factory=dict)
    features_used: int = 0
    regime: str = "unknown"
    timestamp: float = 0.0

    @property
    def is_actionable(self) -> bool:
        return self.direction in ("LONG", "SHORT")

    def to_dict(self) -> Dict:
        return {
            "symbol": self.symbol,
            "direction": self.direction,
            "confidence": self.confidence,
            "edge": self.edge,
            "predicted_class": self.predicted_class,
            "probabilities": self.probabilities,
            "features_used": self.features_used,
            "regime": self.regime,
            "timestamp": self.timestamp,
        }


class MLSignalEngine:
    """
    Real-time ML signal generation engine.

    Maintains a rolling buffer of OHLCV candles per symbol,
    computes v2 features on each new closed candle, and runs
    the trained model for signal generation.
    """

    # Minimum candles needed for feature computation
    MIN_CANDLES = 60  # Need at least 50-bar lookback + buffer

    def __init__(
        self,
        model: Any = None,
        feature_names: Optional[List[str]] = None,
        norm_params: Optional[Dict] = None,
        min_confidence: float = 0.42,
        min_edge: float = 0.05,
        buffer_size: int = 200,
    ):
        self._model = model
        self._feature_names = feature_names or []
        self._norm_params = norm_params or {}
        self._min_confidence = min_confidence
        self._min_edge = min_edge
        self._buffer_size = buffer_size

        # Rolling candle buffers per symbol
        self._buffers: Dict[str, deque] = {}

        # Feature engine (lazy import to avoid circular deps)
        self._feature_engine = None

        # Signal callbacks
        self._on_signal: Optional[Callable[[TradingSignal], None]] = None

        # Stats
        self._signals_generated = 0
        self._candles_processed = 0

    def on_signal(self, callback: Callable[[TradingSignal], None]):
        """Register signal callback."""
        self._on_signal = callback

    def load_model(self, model_path: str):
        """Load a trained model from disk."""
        import joblib
        model_data = joblib.load(model_path)

        if isinstance(model_data, dict):
            self._model = model_data.get("model")
            self._feature_names = model_data.get("feature_names", [])
            self._norm_params = model_data.get("norm_params", {})
            logger.info(
                "Model loaded: %d features, norm_params=%s",
                len(self._feature_names), bool(self._norm_params),
            )
        else:
            self._model = model_data
            logger.info("Model loaded (raw, no metadata)")

    def initialize_buffer(self, symbol: str, historical_candles: pd.DataFrame):
        """
        Pre-fill the candle buffer with historical data.
        Called at startup to avoid waiting for MIN_CANDLES real-time candles.
        """
        self._buffers[symbol] = deque(maxlen=self._buffer_size)

        for _, row in historical_candles.iterrows():
            candle = {
                "open_time": row.get("open_time", 0),
                "open": float(row.get("open", 0)),
                "high": float(row.get("high", 0)),
                "low": float(row.get("low", 0)),
                "close": float(row.get("close", 0)),
                "volume": float(row.get("volume", 0)),
            }
            self._buffers[symbol].append(candle)

        logger.info("Buffer initialized for %s: %d candles", symbol, len(self._buffers[symbol]))

    def process_candle(
        self,
        symbol: str,
        open_time: int,
        open_price: float,
        high: float,
        low: float,
        close: float,
        volume: float,
        is_closed: bool,
    ) -> Optional[TradingSignal]:
        """
        Process a new candle. Only generates signals on closed candles.

        Returns:
            TradingSignal if actionable signal generated, None otherwise.
        """
        if not is_closed:
            return None

        self._candles_processed += 1

        # Add to buffer
        if symbol not in self._buffers:
            self._buffers[symbol] = deque(maxlen=self._buffer_size)

        candle = {
            "open_time": open_time,
            "open": open_price,
            "high": high,
            "low": low,
            "close": close,
            "volume": volume,
        }
        self._buffers[symbol].append(candle)

        # Check minimum candles
        if len(self._buffers[symbol]) < self.MIN_CANDLES:
            logger.debug(
                "%s: %d/%d candles buffered, waiting...",
                symbol, len(self._buffers[symbol]), self.MIN_CANDLES,
            )
            return None

        # Generate signal
        try:
            signal = self._generate_signal(symbol)
            if signal and signal.is_actionable:
                self._signals_generated += 1
                if self._on_signal:
                    self._on_signal(signal)
                return signal
        except Exception as e:
            logger.error("Signal generation error for %s: %s", symbol, e)

        return None

    def _generate_signal(self, symbol: str) -> Optional[TradingSignal]:
        """Run the ML pipeline: features → normalize → predict → filter."""
        if self._model is None:
            logger.warning("No model loaded, skipping signal generation")
            return None

        # Build DataFrame from buffer
        df = pd.DataFrame(list(self._buffers[symbol]))

        # Compute features
        features_df = self._compute_features(df)
        if features_df is None or features_df.empty:
            return None

        # Get latest feature row
        latest = features_df.iloc[-1:]

        # Select and order features
        if self._feature_names:
            available = [f for f in self._feature_names if f in latest.columns]
            if len(available) < len(self._feature_names) * 0.8:
                logger.warning(
                    "%s: Only %d/%d features available",
                    symbol, len(available), len(self._feature_names),
                )
                return None
            X = latest[available].copy()
            # Fill missing features with 0
            for f in self._feature_names:
                if f not in X.columns:
                    X[f] = 0.0
            X = X[self._feature_names]
        else:
            X = latest.select_dtypes(include=[np.number])

        # Normalize using training params
        if self._norm_params:
            means = self._norm_params.get("means", {})
            stds = self._norm_params.get("stds", {})
            for col in X.columns:
                if col in means and col in stds and stds[col] > 0:
                    X[col] = (X[col] - means[col]) / stds[col]

        # Replace NaN/inf
        X = X.replace([np.inf, -np.inf], np.nan).fillna(0)

        # Predict
        try:
            proba = self._model.predict_proba(X.values)[0]
        except Exception as e:
            logger.error("Model prediction error: %s", e)
            return None

        # Parse probabilities (0=SHORT, 1=NEUTRAL, 2=LONG)
        p_short = proba[0] if len(proba) > 0 else 0
        p_neutral = proba[1] if len(proba) > 1 else 0
        p_long = proba[2] if len(proba) > 2 else 0

        predicted_class = int(np.argmax(proba))
        confidence = float(np.max(proba))

        # Determine direction and edge
        if predicted_class == 2:  # LONG
            direction = "LONG"
            edge = p_long - p_neutral
        elif predicted_class == 0:  # SHORT
            direction = "SHORT"
            edge = p_short - p_neutral
        else:
            direction = "NEUTRAL"
            edge = 0.0

        # Detect regime from features
        regime = self._detect_regime(features_df)

        # Apply filters
        if confidence < self._min_confidence:
            direction = "NEUTRAL"
        if edge < self._min_edge:
            direction = "NEUTRAL"

        signal = TradingSignal(
            symbol=symbol,
            direction=direction,
            confidence=confidence,
            edge=edge,
            predicted_class=predicted_class,
            probabilities={"short": p_short, "neutral": p_neutral, "long": p_long},
            features_used=len(X.columns),
            regime=regime,
            timestamp=time.time(),
        )

        logger.info(
            "SIGNAL: %s %s conf=%.3f edge=%.3f regime=%s P(L/N/S)=%.2f/%.2f/%.2f",
            symbol, direction, confidence, edge, regime, p_long, p_neutral, p_short,
        )

        return signal

    def _compute_features(self, df: pd.DataFrame) -> Optional[pd.DataFrame]:
        """Compute v2 features from OHLCV data."""
        if self._feature_engine is None:
            try:
                from ai.features.engine_v2 import FeatureEngineV2
                self._feature_engine = FeatureEngineV2()
            except ImportError:
                try:
                    from ai.features.engine import FeatureEngine
                    self._feature_engine = FeatureEngine()
                except ImportError:
                    logger.error("No feature engine available")
                    return None

        try:
            return self._feature_engine.compute(df)
        except Exception as e:
            logger.error("Feature computation error: %s", e)
            return None

    def _detect_regime(self, features_df: pd.DataFrame) -> str:
        """Detect market regime from computed features."""
        if features_df.empty:
            return "unknown"

        latest = features_df.iloc[-1]

        # Use volatility regime feature if available
        if "vol_regime" in latest.index:
            vol = latest["vol_regime"]
            if vol > 1.5:
                return "high_vol"
            elif vol < 0.5:
                return "low_vol"

        # Use trend strength if available
        if "trend_strength_20" in latest.index:
            trend = latest["trend_strength_20"]
            if trend > 0.6:
                return "trending"
            elif trend < -0.6:
                return "trending_down"

        return "neutral"

    def get_stats(self) -> Dict:
        """Get signal engine statistics."""
        return {
            "model_loaded": self._model is not None,
            "feature_names_count": len(self._feature_names),
            "has_norm_params": bool(self._norm_params),
            "buffers": {s: len(b) for s, b in self._buffers.items()},
            "candles_processed": self._candles_processed,
            "signals_generated": self._signals_generated,
            "min_confidence": self._min_confidence,
            "min_edge": self._min_edge,
        }
